USE HD_REPOZYTORIUM_GLOWNE

INSERT INTO OPIS (pierwszy_opis,drugi_opis,start_time_opis,duration_opis)
SELECT  DISTINCT DESCRIPTION_TYM,ND_DESCRIPTION_TYM,start_time2,DURATION_TYM
FROM [HD_REPOZYTORIUM_GLOWNE].[dbo].[DANE_GLOWNE_TYM2]
Where DESCRIPTION_TYM is not null