UPDATE [HD_REPOZYTORIUM_GLOWNE].[dbo].[DANE_GLOWNE_TYM]
SET VARIABLE_TARGET_TYM = 'RCH%'
WHERE VARIABLE_TARGET_TYM ='RCH %  [Not cons. - TH: 0min.]';
UPDATE [HD_REPOZYTORIUM_GLOWNE].[dbo].[DANE_GLOWNE_TYM]
SET VARIABLE_TARGET_TYM = 'RCH'
WHERE VARIABLE_TARGET_TYM ='RCH  [Not cons. - TH: 0min.]';

INSERT INTO DANE_GLOWNE_TYM2
SELECT * FROM DANE_GLOWNE_TYM
UNPIVOT (a FOR grupa_charakterystyk IN([Total Individuals]
      , [Podgrupa]
      , [A16-49]
      , [M16-49]
      , [A4-15]
      , [A4-9])) up
PIVOT (MAX(a) FOR VARIABLE_TARGET_TYM IN([AMR],[AMR %],[SHR %],[RCH%],[RCH])) as p