USE [HD_REPOZYTORIUM_GLOWNE]
GO

UPDATE HD_REPOZYTORIUM_GLOWNE.[dbo].DANE_GLOWNE_TYM2
SET CHANNEL_TYM =  REPLACE(CHANNEL_TYM, SUBSTRING(CHANNEL_TYM, charindex('[', CHANNEL_TYM), Charindex(']', CHANNEL_TYM)), '')   from DANE_GLOWNE_TYM2;